CREATE TABLE documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name VARCHAR(225) NOT NULL,
  document_type VARCHAR(225) NOT NULL,
  booking_center VARCHAR(225) NOT NULL,
  cif VARCHAR(225) NOT NULL,
  content_type VARCHAR(225) NOT NULL,
  content BLOB NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_by VARCHAR(225),
  created_date TIMESTAMP,
  updated_by VARCHAR(225),
  updated_date TIMESTAMP
);
